version: '3'

services:
  waldur_site_agent_pull:
    image: opennode/waldur-site-agent:latest
    env_file:
      waldur-agent-pull-env
    volumes: # Add this if SLURM cluster deployed in Docker
      - /var/run/docker.sock:/var/run/docker.sock

  waldur_site_agent_push:
    image: opennode/waldur-site-agent:latest
    env_file:
      waldur-agent-push-env
    volumes: # Add this if SLURM cluster deployed in Docker
      - /var/run/docker.sock:/var/run/docker.sock
